server:
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/project_A
    username: root
    password: 1234

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要對應mapper映射xml文件的所在路徑
  configuration:
    #org.apache.ibatis.logging.stdout.StdOutImpl 控制檯打印sql語句方便調試sql語句執行錯誤
    #org.apache.ibatis.logging.log4j2.Log4j2Impl:這個不在控制檯打印查詢結果,但是在log4j中打印
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    mapUnderscoreToCamelCase: true # 開啓駝峯命名轉換法

logging:
  config: classpath:log4j2.xml
  level:
    #這個指定你的dao層，也就是mapper文件的所在包
    com.project.server.mapper: DEBUG
